/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sunrisedentalclinic.views;

/**
 *
 * @author user
 */

public class BillingView extends javax.swing.JFrame {
    
    private sunrisedentalclinic.models.Receipt currentReceipt = null;
    /**
     * Creates new form BillingView
     */
    public BillingView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtApptId = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceiptArea = new javax.swing.JTextArea();
        btnPrintReceipt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Billing");

        jLabel2.setText("Enter Appointment ID");

        txtApptId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApptIdActionPerformed(evt);
            }
        });

        btnCalculate.setText("Calculate Bill");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        txtReceiptArea.setColumns(20);
        txtReceiptArea.setRows(5);
        jScrollPane1.setViewportView(txtReceiptArea);

        btnPrintReceipt.setText("Save Receipt");
        btnPrintReceipt.setEnabled(false);
        btnPrintReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(213, 213, 213))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalculate)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrintReceipt))
                    .addComponent(jLabel2)
                    .addComponent(txtApptId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtApptId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate)
                    .addComponent(btnPrintReceipt))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApptIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApptIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApptIdActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
       String apptIdStr = txtApptId.getText().trim();
    
    if (apptIdStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter an Appointment ID.");
        return;
    }

    sunrisedentalclinic.controllers.BillingController controller = new sunrisedentalclinic.controllers.BillingController();
    currentReceipt = controller.calculateTotal(apptIdStr);

    if (currentReceipt == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Billing details not found for ID " + apptIdStr, "Not Found", javax.swing.JOptionPane.ERROR_MESSAGE);
        txtReceiptArea.setText("");
        btnPrintReceipt.setEnabled(false);
    } else {
    
        String billText = 
            "==========================================\n" +
            "          SUNRISE DENTAL CLINIC           \n" +
            "          BILLING STATEMENT               \n" +
            "==========================================\n\n" +
            "  APPOINTMENT NO :  " + currentReceipt.getAppointmentID() + "\n" +
            "  PATIENT NAME   :  " + currentReceipt.getPatientName() + "\n" +
            "  DENTIST        :  " + currentReceipt.getDentistName() + "\n\n" +
            "------------------------------------------\n" +
            "  TREATMENT      :  " + currentReceipt.getTreatmentName() + "\n" +
            "  TREATMENT COST :  LKR " + String.format("%.2f", currentReceipt.getTreatmentCost()) + "\n" +
            "  HOSPITAL FEE   :  LKR " + String.format("%.2f", currentReceipt.getConsultationFee()) + "\n" +
            "------------------------------------------\n" +
            "  TOTAL DUE      :  LKR " + String.format("%.2f", currentReceipt.getTotalAmount()) + "\n" +
            "==========================================\n" +
            " Please review the charges above. Click \n" +
            " 'Print & Save Receipt' to finalize. \n";
            
        txtReceiptArea.setText(billText);
        btnPrintReceipt.setEnabled(true); 
    }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnPrintReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReceiptActionPerformed
       if (currentReceipt == null) {
        return;
    }
    
    sunrisedentalclinic.controllers.BillingController controller = new sunrisedentalclinic.controllers.BillingController();
    
    if (controller.confirmPayment(currentReceipt)) {
        String finalText = txtReceiptArea.getText().replace("BILLING STATEMENT", "OFFICIAL RECEIPT (PAID)");
        finalText = finalText.replace("Please review the charges above. Click \n 'Print & Save Receipt' to finalize.", "Payment Received. Thank you!");
        txtReceiptArea.setText(finalText);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Receipt saved to database successfully!");
        
        btnPrintReceipt.setEnabled(false);
        currentReceipt = null; 
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Action Denied, This appointment has already been billed or there is a database error.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnPrintReceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(BillingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(BillingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(BillingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(BillingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new BillingView().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnPrintReceipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApptId;
    private javax.swing.JTextArea txtReceiptArea;
    // End of variables declaration//GEN-END:variables
}
