/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sunrisedentalclinic.views;

/**
 *
 * @author user
 */
public class RegisterAppointView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterAppointView
     */
    public RegisterAppointView() {
        initComponents();
        populateComboBoxes();
    }

    private void populateComboBoxes() {
        sunrisedentalclinic.controllers.AppointmentController controller = new sunrisedentalclinic.controllers.AppointmentController();

        dentistBox.removeAllItems();
        treatmentBox.removeAllItems();

        for (String dentist : controller.loadAvailableDentists()) {
            dentistBox.addItem(dentist);
        }

        for (String treatment : controller.loadAvailableTreatments()) {
            treatmentBox.addItem(treatment);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        patientnameTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        contactTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dentistBox = new javax.swing.JComboBox<>();
        treatmentBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        dateandtimeTxt = new javax.swing.JTextField();
        registerApptBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Register an appointment");

        jLabel2.setText("Patient Name");

        jLabel3.setText("Address");

        jLabel4.setText("Contact Number");

        jLabel5.setText("Dentist");

        jLabel6.setText("Treatment");

        dentistBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        treatmentBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Date and Time");

        registerApptBTN.setText("Register Appointment");
        registerApptBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerApptBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(patientnameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(addressTxt)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(contactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dentistBox, 0, 121, Short.MAX_VALUE)
                                    .addComponent(treatmentBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateandtimeTxt)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(registerApptBTN)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(patientnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(contactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dentistBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(treatmentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dateandtimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registerApptBTN)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerApptBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerApptBTNActionPerformed
        String pName = patientnameTxt.getText().trim();
        String address = addressTxt.getText().trim();
        String contact = contactTxt.getText().trim();
        
        if (dentistBox.getSelectedItem() == null || treatmentBox.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please wait for the dentists and treatment to load");
            return;
        }
        
        String dentist = dentistBox.getSelectedItem().toString();
        String treatment = treatmentBox.getSelectedItem().toString();
        String dateTimeInput = dateandtimeTxt.getText().trim();

        if (pName.isEmpty() || address.isEmpty() || contact.isEmpty() || dateTimeInput.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill all the fields");
            return;
        }
        
        if (!contact.matches("^0\\d{9}$")){
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter a valid 10 digit contact number (eg: 0771234567",
                    "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        }

        java.time.LocalDateTime appointmentDateTime;
        try {
            java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
            appointmentDateTime = java.time.LocalDateTime.parse(dateTimeInput, formatter);
            
            if (appointmentDateTime.isBefore(java.time.LocalDateTime.now())) {
                javax.swing.JOptionPane.showMessageDialog(this, "You cannot book an appointment in the past!", "Timeline Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (java.time.format.DateTimeParseException e){
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Invalid Date/Time format or invalid time (like 25:00).\n" +
                            "Please use YYYY-MM-DD HH:MM (24-hour format).\n" +
                            "Example: 2026-09-05 14:00",
                    "Format Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String date = appointmentDateTime.toLocalDate().toString();
        String time = appointmentDateTime.toLocalTime().toString(); 
        
        sunrisedentalclinic.controllers.AppointmentController controller = new sunrisedentalclinic.controllers.AppointmentController();
        
        if (!controller.isSlotAvailable(dentist, date, time)) {
            javax.swing.JOptionPane.showMessageDialog(this, "This time slot is already booked for " + javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        sunrisedentalclinic.models.Patient patient = new sunrisedentalclinic.models.Patient(pName, address, contact);
        sunrisedentalclinic.models.Appointment appt = new sunrisedentalclinic.models.Appointment(dentist, treatment, date, time);
        
         if (controller.processRegistration(patient, appt)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Appointment Registered Succesfully");
            
            patientnameTxt.setText("");
            addressTxt.setText("");
            contactTxt.setText("");
            dateandtimeTxt.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Registration failed, check the server connection", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_registerApptBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterAppointView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterAppointView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterAppointView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterAppointView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterAppointView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JTextField contactTxt;
    private javax.swing.JTextField dateandtimeTxt;
    private javax.swing.JComboBox<String> dentistBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField patientnameTxt;
    private javax.swing.JButton registerApptBTN;
    private javax.swing.JComboBox<String> treatmentBox;
    // End of variables declaration//GEN-END:variables
}
